Input/Output of Statmech Calculations
ReactionMechanismGenerator/AutoTST pull request #83
Opened 2020-06-09 15:11 UTC by nateharms

When creating Arkane input files for species and transition states, we would first check to make sure that an Arkane input file was created and if it was created, we would not create a new one on the assumption that this was correct. This PR allows for new files to be written and if an old file exists, it will be written as a backup file in case a user wants to keep it.

2020-06-16 17:56 UTC, davidfarinajr commented
@nateharms, can you rebase this branch onto master? I think there are some commits here we already merged in

2020-06-16 18:15 UTC, nateharms commented
Okay, I rebased

2020-10-15 21:15 UTC, nateharms commented
Because this PR is a little old, here's a summary of the changes:

`calculator/statmech.py`
* Added a few imports
* Added former rotor treatment for stable species
* Added a try / except for running kinetics with rotors and then without if Arkane fails

`species.py`
* reorganized when certain attributes are set

`data/inputoutput.py`
* added `TemplateReaction` to the `read_kinetics_file` method

`job/job.py`
* removed an import

2020-10-15 21:15 UTC, nateharms commented
@skrsna could you give this one a look over too?

2020-10-20 00:48 UTC, skrsna requested changes

2020-10-20 00:48 UTC, skrsna commented on autotst/calculator/statmech.py
> +        except:
maybe add the exact Error you get from this `try/except` block. Plain `except` will catch everything (even an KeyboardInterupt)

2020-10-20 00:48 UTC, skrsna commented on autotst/calculator/statmech.py
> +        except:
same here. Try to catch the exact Errors and maybe log them as well

2020-10-20 00:48 UTC, skrsna commented on autotst/calculator/statmech.py
>          if os.path.exists(os.path.join(self.directory, "species", label, label + '.py')):
maybe move the `old_path` or rename it to PATH and check it 
e.g. 
```
PATH = os.path.join(self.directory, "species", label, label + '.py'
if os.path.exists(PATH):
   logging.info(f"Species input file already written... Renaming it {old_path} and creating a new one.")
             shutil.move(
                 PATH,
                 PATH.replace('py', 'old.py')
             )
```

2020-10-20 00:48 UTC, skrsna commented on autotst/calculator/statmech.py
>          if os.path.exists(os.path.join(self.directory, "ts", label, label + '.py')):
same comment as above :)

2020-10-20 14:34 UTC, nateharms commented
@skrsna the corrections that you requested were made. When you get a chance, can you approve this PR?

2020-10-20 14:49 UTC, skrsna approved these changes

2020-10-20 15:20 UTC, merged